zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    
    balance:
      path: /balance/**
      service-id: cpcr-balance
      sensitive-headers: '*'
    boss:
      path:  /boss/**
      service-id: cpcr-boss
      sensitive-headers: '*'
    reconcil:
      path:  /reconcil/**
      service-id: cpcr-reconcil
      sensitive-headers: '*'
    auth:
      path:  /auth/**
      service-id: cloud-auth
      sensitive-headers: '*'
    mch:
      path:  /mch/**
      service-id: cpcr-mch
      sensitive-headers: '*'    
    alarm:
      path:  /alarm/**
      service-id: nova-alarm
      sensitive-headers: '*'     
    eva:
      path:  /eva/**
      service-id: nova-eva
      sensitive-headers: '*'     
    file:
      path:  /file/**
      service-id: nova-file
      sensitive-headers: '*'       
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

  

management:
  security:
    enabled: false
    
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8762/auth/oauth/token
      user-authorization-uri: http://localhost:8762/auth/oauth/authorize
      client-id: webapp
    resource:
      user-info-uri: http://localhost:8762/auth/user
      prefer-token-info: false
      
test:
  get: test
  
#################################################################################################################################
spring:
  application:
    name: cloud-gateway
  cloud:
    bus:
      trace:
        enable: true
  rabbitmq:
    host: 111.230.38.240
    port: 5672
    username: nova
    password: Nova2017
    
server:
  port: 8762

auth.urls: http://192.168.31.159:8762/boss

# 支付路由对应的名称,前面要加 "/"
auth.routs: /boss
  