
server:
  port: 8768

spring:
  rabbitmq:
    host: 120.77.37.110
    port: 5000
    username: nova
    password: Nova2017
    publisher-confirms: true
    publisher-returns: true
    template.mandatory: true
